Repository Xilinx/brevitas, pull requests merged in 2024-02, with the labels that each got.

#828 Fix (examples/super_res): updating README
  src/brevitas_examples/super_resolution/README.md
Labels: next release

#835 Fix: typo fix in applying bias correction
  src/brevitas_examples/llm/llm_quant/bias_corr.py
Labels: next release

#838 Fix (examples/export): improved export
  src/brevitas_examples/llm/main.py
  src/brevitas_examples/stable_diffusion/main.py
Labels: next release

#813 Feat (examples/a2q): adding CIFAR10 example
  src/brevitas_examples/imagenet_classification/a2q/README.md
  src/brevitas_examples/imagenet_classification/a2q/__init__.py
  src/brevitas_examples/imagenet_classification/a2q/a2q_evaluate_models.py
  src/brevitas_examples/imagenet_classification/a2q/a2q_train_models.py
  src/brevitas_examples/imagenet_classification/a2q/ep_init.py
  src/brevitas_examples/imagenet_classification/a2q/quant.py
  src/brevitas_examples/imagenet_classification/a2q/resnet.py
  src/brevitas_examples/imagenet_classification/a2q/utils.py
  tests/brevitas_examples/test_examples_import.py
Labels: next release

#853 Fix (examples/llm): set `group_size` only for groupwise quantization
  src/brevitas_examples/common/generative/quantize.py
Labels: bug

#860 feat (gen/quantize): Added device flag to `quantize_model`
  src/brevitas_examples/common/generative/quantize.py
Labels: next release

#839 Fix (core): deprecate bitwidth-less bias
  src/brevitas/nn/mixin/base.py
  src/brevitas/nn/mixin/parameter.py
  src/brevitas/nn/quant_layer.py
  src/brevitas/proxy/parameter_quant.py
  src/brevitas/quant/fixed_point.py
  src/brevitas/quant/none.py
  src/brevitas/quant/scaled_int.py
  src/brevitas/quant/solver/bias.py
  src/brevitas_examples/bnn_pynq/README.md
  src/brevitas_examples/bnn_pynq/models/resnet.py
  src/brevitas_examples/imagenet_classification/models/mobilenetv1.py
  src/brevitas_examples/imagenet_classification/models/proxylessnas.py
  src/brevitas_examples/imagenet_classification/qat/README.md
  src/brevitas_examples/imagenet_classification/utils.py
  tests/brevitas/nn/test_hadamard.py
  tests/brevitas/nn/test_linear.py
Labels: refactoring
