Repository Xilinx/brevitas, pull requests merged in 2024-03, with the labels that each got.

#884 Infra: Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#805 Feat: Add QuantConv3d and QuantConv3dTranspose
  src/brevitas/export/onnx/handler.py
  src/brevitas/export/onnx/standard/qoperator/handler/parameter.py
  src/brevitas/export/onnx/standard/qoperator/manager.py
  src/brevitas/export/torch/qoperator/handler/parameter.py
  src/brevitas/export/torch/qoperator/manager.py
  src/brevitas/graph/fixed_point.py
  src/brevitas/graph/gpfq.py
  src/brevitas/graph/gptq.py
  src/brevitas/graph/gpxq.py
  src/brevitas/graph/per_input.py
  src/brevitas/graph/quantize.py
  src/brevitas/graph/target/flexml.py
  src/brevitas/graph/utils.py
  src/brevitas/nn/__init__.py
  src/brevitas/nn/quant_conv.py
  src/brevitas/nn/quant_convtranspose.py
  tests/brevitas/export/quant_module_fixture.py
  tests/brevitas/export/test_torch_qcdq.py
  tests/brevitas/graph/test_transforms.py
  tests/brevitas/nn/nn_quantizers_fixture.py
  tests/brevitas/nn/test_a2q.py
  tests/brevitas/nn/test_conv3d.py
  tests/brevitas/nn/test_convtranspose.py
  tests/brevitas/nn/test_wbiol.py
  tests/brevitas_ort/common.py
  tests/brevitas_ort/test_quant_module.py
Labels: good first issue, nn, feature

#902 Remove: Remove original_cat workaround
  src/brevitas/__init__.py
  src/brevitas/graph/quantize_impl.py
  src/brevitas/quant_tensor/torch_handler.py
Labels: refactoring

#885 Pull Request Template
  .github/pull_request_template.md
Labels: documentation
